x = input('Digite um valor: ')
print('O tipo primitivo dessa classe é:', type(x))
print('Só tem espaços: ', x.isspace())
print('É um número?', x.isnumeric())
print('É albabetico?', x.isalpha())
print('É alafanumerico?', x.isalnum())
print('Está em maiúsculo?', x.isupper())
print('Está em minúsculo?', x.islower())
print('Está capitalizada?', x.istitle)